from livepublication_portal.views.home_view import home
from livepublication_portal.views.flow_views.HelloWorld_flow_view import hello_flow
from livepublication_portal.views.flow_views.BeeMovie_flow_view import bee_flow
from livepublication_portal.views.flow_views.ls_flow_view import ls_flow
from livepublication_portal.views.publications_view import publications
from livepublication_portal.views.system_status_view import system_status
from livepublication_portal.views.control_centre_view import control_centre

